name: Ruff
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          args: "--select E,F,N,D,UP,PYI,SLOT,SIM,TD,FIX,W,PL --ignore E501 --respect-gitignore"

